# Generated by Django 4.2 on 2023-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
