# Generated by Django 4.2 on 2023-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomment_datetime_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_view',
            field=models.IntegerField(default=0),
        ),
    ]
